apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect4-client
  labels:
    app: connect4-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect4-client
      version: v1
  template:
    metadata:
      labels:
        app: connect4-client
        version: v1
    spec:
      containers:
      - image: docker.io/{{YOUR_USERNAME}}/connect4-client:{{IMAGE_TAG}}
        imagePullPolicy: Always
        name: connect4-client
        ports:
        - containerPort: 3000
        env:
          - name: API_URL
            value: "https://connect4-server.{{YOUR_TEAMNAME}}.hgopteam.com"
